services:
  postgres:
    container_name: url-shortener-postgres
    image: "postgres:15-alpine"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 40s

  app:
    image: ghcr.io/larsniet/url-shortener-api:main
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - APP_HOST=http://localhost:8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/health-check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
