services:
  postgres:
    container_name: url-shortener-postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    env_file:
      - .env

  app:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
