services:
  postgres:
    container_name: url-shortener-postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/health-check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
